### ISSUE TITLE
Example code not working out of the box

### ISSUE THREAD

**Issue by avhansen** [OfficeDev/SharePoint_SP-hosted_Add-Ins_Tutorials#1]
Hi
I'm following the tutorial [Get started creating SharePoint-hosted SharePoint Add-ins](https://msdn.microsoft.com/en-us/library/office/fp142379.aspx)

If you already have an Office 365 subscription and sets up a developer site (as instructed under "Set up your dev environment" in the tutorial) you get a developer site like
`companyname.sharepoint.com/sites/dev`.

In step 29 under "Code you app" the link in the snippet doesn't work
` <p>
  <asp:HyperLink runat="server" 
       NavigateUrl="/EmployeeOrientation/Lists/NewEmployeesInSeattle/AllItems.aspx" 
       Text="New Employees in Seattle" />
</p>`

since this will link to `https://companyname-[appid123].sharepoint.com/EmployeeOrientation/Lists/NewEmployeesInSeattle/AllItems.aspx`
in the browser and not 
`https://companyname-[appid123].sharepoint.com/sites/dev/EmployeeOrientation/Lists/NewEmployeesInSeattle/AllItems.aspx`
as expected.

Wouldn't it be better to use a relative link in step 29 like `../Lists/NewEmployeesInSeattle/AllItems.aspx`?

**Comment by Rick-Kirkham** [comment]
avhansen,
I cannot reproduce any problems. You say the snippet doesn't work. What error do you get?
The URL for the list view page ...  https://companyname-[appid123].sharepoint.com/EmployeeOrientation/Lists/NewEmployeesInSeattle/AllItems.aspx 
is correct. 
The alternative you suggested ... https://companyname-[appid123].sharepoint.com/sites/dev/EmployeeOrientation/Lists/NewEmployeesInSeattle/AllItems.aspx 
... is not a valid URL because "/sites/dev" is not a site under the add-in domain: companyname-[appid123].sharepoint.com. It is a site under the host domain:  companyname.sharepoint.com

**Comment by avhansen** [comment]
I have followed the tutorial step by step and that's not what I'm seeing.

I created a developer site as instructed [here](https://msdn.microsoft.com/en-us/library/office/jj692554.aspx).

After adding the new developer site as the "site URL" in the project properties and then pressing F5 to run the app, the app opens up at the url
https://companyname-[appid123].sharepoint.com/**sites/dev/**EmployeeOrientation/Pages/Default.aspx

When I click "New Employees in Seattle" I'm taken to:
https://companyname-[appid123].sharepoint.com/EmployeeOrientation/Lists/NewEmployeesInSeattle/AllItems.aspx
which is a completely blank page.

However if I go to https://companyname-[appid123].sharepoint.com/**sites/dev**/EmployeeOrientation/Lists/NewEmployeesInSeattle/AllItems.aspx
I see the list.

**Comment by Rick-Kirkham** [comment]
Thanks for the additional details. I can now reproduce the issue. For step 29, please use the following snippet, instead of the snippet in the topic. 

&lt;p&gt;&lt;a onclick="window.location = _spPageContextInfo.webAbsoluteUrl + '/Lists/NewEmployeesInSeattle/AllItems.aspx';" href="#" &gt;New Employees in Seattle&lt;/a&gt;&lt;/p&gt;


I will try to get the topic and the samples updated this week. In the meantime, if you get farther into the series of tutorials before I can fix them, you may run into a parallel problem with other custom links and you will need to make a parallel change to the instructions. 
Thanks for catching this!

**Comment by avhansen** [comment]
It's working now. Thank you!
